repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    # TODO: There's something weird where prettier is hitting node_modules/ even though I added a .prettierignore.
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@^3.2.5
          - prettier-plugin-astro@^0.13.0
          - prettier-plugin-organize-imports@^3.2.4
          - prettier-plugin-tailwindcss@^0.5.14
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^\.astro/types\.d\.ts$
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
